### ISSUE TITLE
vagrant adb box should have the latest docker engine

### ISSUE THREAD

**Issue by bamachrn** [bexelbie/vagrant-adbinfo#85]
While using vagrant-adbinfo plugin with docker client of local machine we get

$ docker ps
Error response from daemon: client is newer than server (client API version: 1.21, server API version: 1.20)

My local machine is having latest version of docker. But the engine in adb box is old one.
We should make changes in the system, so that when one installs vagrant-adbinfo plugin it should automatically update the docker engine of the vagrant box.

**Comment by mohammedzee1000** [comment]
If stability is an issue (as we do stay behind a couple of versions behind upstream for the same reason), we could have user being recommended for downgrade or the same happening automatically on the guest, though i do prefer if the box version gets updated.

**Comment by LalatenduMohanty** [comment]
@bamachrn The ADB Vagrant box is based on CentOS core i.e. it can only have RPMs which is available in CentOS. So we wont be able to go to a docker version which is not present in CentOS.  

I think we should think about how we can ship the docker client through the ADB box and then use the correct/compatible docker client version from the host to communicate

**Comment by bamachrn** [comment]
@LalatenduMohanty This is good. But we should have some way to at least make the client and server versions in the same native api version. As it is not backward compatible, and user will face trouble.

We should get a way so that the user need not to think about the version management.

**Comment by mohammedzee1000** [comment]
So basically we need to figure out how to run 2 versions of docker client seamlessly on a system, or we could inform the user and with his permission, downgrade the client automatically.

**Comment by LalatenduMohanty** [comment]
https://github.com/projectatomic/vagrant-adbinfo/issues/85#issuecomment-178416626

Agree

**Comment by LalatenduMohanty** [comment]
@bamachrn Agree with you. User should not have to think about it.

@mohammedzee1000 these things can be handled automatically we we create single click installers for ADB.  But yes, we need to find a way to do that, then automate + integrate it

**Comment by mohammedzee1000** [comment]
Few things we could try (this problem will arise especially in the dev environment than the ops one)
- If there is a version mismatch, create another vagrant vm with docker client of appropriate version installed and route docker traffic from there.(suggestion from shubam).
- Package the docker client of appropriate version with a slightly modified name 'adb-docker' (this coud be done through links as well. ie newname link pointing to packaged docker client in respective users bin directory) for example.
- Check for version mismatch, and with users permission, upgrade or downgrade accordingly.

**Comment by concaf** [comment]
In addition to what @mohammedzee1000 has suggested,

Instead of using Docker CLI client on the base machine, can [Remote API](https://docs.docker.com/engine/reference/api/docker_remote_api/) or one of these [Remote API clients](https://docs.docker.com/engine/reference/api/remote_api_client_libraries/) be used to access Docker in the Vagrant VM? This way upgrading or downgrading Docker on the base machine does not have to be worried about, and this will also work across platforms.

However, in the case of using:

[Remote API](https://docs.docker.com/engine/reference/api/docker_remote_api/):
- Multiple API versions have to be supported.
- Effectively, this is like maintaining a new Docker Remote API client.

[Remote API client](https://docs.docker.com/engine/reference/api/remote_api_client_libraries/):
- If these are well maintained (Docker does not maintain these, except [docker-py](https://github.com/docker/docker-py)), then each API version does not have to be supported and code remains the same.
- These might not have support for all the Docker CLI client features (even [docker-py](https://github.com/docker/docker-py) does not support 'everything' which the CLI client does).

On another note, how about a hybrid approach? When the Remote API client does not work (feature not supported or version incompatibility), the Remote API can be used to do that thing.

Please correct me if I'm wrong or talking off-track!

**Comment by tuxdna** [comment]
As mentioned by @containscafeine it makes sense to use Remote API.

Since we are not going just upgrade to docker version 1.9 very soon ( because it has technical debt ), we may just as well use REST API. The reason is simple, the underlying VM is really just CentOS, which has docker version 1.2.

We can build simple tools to address the use-cases ( like `docker ps` in this issue ), and provide a seamless integration with the REST API endpoints rather than depending on docker server/client version compatibility.

**Comment by bamachrn** [comment]
I would like to add few things here.
1. External docker client is only required when we are exporting environment variables to the local machine.
2. In other scenarios we do not need external docker client.

So what I was having in mind is why don't we just add one more environment variable export to the existing set. This will redirect all the commands from the local machine, which in turn will use the docker client inside the adb vagrant box.

we just need a way to redirect the commands to the internal docker client this will help in all the cases including windows, mac.

I believe we should not do any changes to the users local machine.

I am working for the same to get a way to use the internal docker client. Please suggest if something else is in mind.

**Comment by tuxdna** [comment]
@bamachrn The question then is "who will use that extra environment variable"? Will this be 
- the docker client OR 
- a tool that can understand this variable and forward the commands to the docker in VM

We would still need some running code ( or a tool ) that understands this extra env variable.

**Comment by bamachrn** [comment]
@tuxdna extra environment variable is for the local users machine.  When user exports the docker host variable using `eval "$(vagrant adfinfo)"`, this one will also get added. So User will not see any changes in behavior. And this will work seamlessly. 
If the user wants to use vagrant ssh or eclipse, this env variable will not be exported hence it will not have any effect to users environment.

**Comment by tuxdna** [comment]
@bamachrn that doesn't address the question that which running code ( or tool ) will actually understand this extra environment variable.

Perhaps you are saying that this environment variable might indicate to the tool to forward requests over SSH. That will work, but the question is what code is going to do that? Obviously docker version 1.9 doesn't do it at the moment.

**Comment by bamachrn** [comment]
@tuxdna yes I am working for the same to find out a way to do that.

**Comment by tuxdna** [comment]
@bamachrn great! You can put your ideas here, or let me know we can collaborate on it.

**Comment by hferentschik** [comment]
Is this not a similar discussion to the oc client? I think the optimal solution would be, if the VM could contain the matching Docker and OpenShift CLI (for all OS types) and adbinfo (resp. its successor service-manager) allows to copy them out to the host. The plugin cloud in this case also detect the OS type automatically. For example:

```
$ vagrant service-manager docker copy-client
```

and

```
$ vagrant service-manager openshift copy-client
```

The user can then decide whether he wants to execute the CLI locally (from the same directory) like `./docker` or whether he wants to update its `PATH` temporarily/permanently.

**Comment by praveenkumar** [comment]
@hferentschik Yes we can cache oc and docker binary to ADB/CDK box but it might be using a rpm because build system don't have external network connectivity. I will discuss with @LalatenduMohanty  and find out what would be a good solution for cache those binaries.

**Comment by navidshaikh** [comment]
> find out what would be a good solution for cache those binaries.

How about including the binaries in adb-utils?

**Comment by praveenkumar** [comment]
> How about including the binaries in adb-utils?

Adding binary into RPM package which something I avoid because it violate RPM packaging Guideline.

https://fedoraproject.org/wiki/Packaging:Guidelines#No_inclusion_of_pre-built_binaries_or_libraries

**Comment by hferentschik** [comment]
where is rpm involved here?

**Comment by praveenkumar** [comment]
> where is rpm involved here?

How do you suggest to include those binaries then?

**Comment by navidshaikh** [comment]
This issue was moved to projectatomic/vagrant-service-manager#3
